os: linux
language: java
jdk: oraclejdk8
cache:
  directories: $HOME/.m2
env:
  - HEROKU_API_KEY: $HEROKU_API_KEY
sudo: required
services: docker
addons:
  apt:
    packages: oracle-java8-installer
script:
  - chmod +x mvnw #- ./mvnw clean test
  - ./mvnw clean package -Pprod -DskipTests docker:build
  - cd target/docker/
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com
  - docker tag core-oauth registry.heroku.com/oauth-contacomigo/web
  - docker push registry.heroku.com/oauth-contacomigo/web
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
