os: linux
language: java
jdk: oraclejdk8
cache:
  directories: $HOME/.m2
env:
  - HEROKU_API_KEY: $HEROKU_API_KEY
sudo: required
addons:
  apt:
    packages: oracle-java8-installer
script:
  - chmod +x mvnw #- ./mvnw clean test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: oauth-contacomigo
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
