os: linux
language: java
jdk: oraclejdk8
cache:
  directories: $HOME/.m2
env:
  - HEROKU_API_KEY: $HEROKU_API_KEY
sudo: required
addons:
  apt:
    packages: oracle-java8-installer
script:
  - chmod +x mvnw #- ./mvnw clean test
  - ./mvnw clean package -Pprod -DskipTests
  - git push heroku master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
