os: linux
language: java
jdk: oraclejdk8
cache:
  directories: $HOME/.m2
sudo: false
addons:
  apt:
    packages: oracle-java8-installer
env:
  spring:
    profiles:
      default: prod
script:
  - chmod +x mvnw #- ./mvnw clean test
  - ./mvnw com.heroku.sdk:heroku-maven-plugin:1.1.1:deploy-war -DskipTests -Pprod -Dheroku.appName=oauth-contacomigo
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
