version: '2'
services:
    oauth-app:
        image: oauth
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=${JHIPSTER_REGISTRY_URL}/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://oauth-mysql:3306/oauth?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    oauth-mysql:
        extends:
            file: mysql.yml
            service: oauth-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
